import type { Metadata } from "next";
import localFont from "next/font/local";
import classNames from "classnames";

import "./globals.css";

const authentic = localFont({
  src: [
    {
      path: "./fonts/AUTHENTICSans-90.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/AUTHENTICSans-130.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-authentic",
});
const authenticCondensed = localFont({
  src: [
    {
      path: "./fonts/AUTHENTICSans-Condensed-90.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-authentic-condensed",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames(
          "min-h-screen font-sans",
          authentic.variable,
          authenticCondensed.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
